{
 "title": "Fraud Detection Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Транзакции в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(transactions_total[5s])", "legendFormat": "TPS" }
   ]
  },
  {
   "title": "Доля мошеннических транзакций",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fraud_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Распределение скоров мошенничества во времени",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(fraud_score_bucket[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Среднее время обработки транзакций",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(transaction_processing_seconds_sum[5s]) / rate(transaction_processing_seconds_count[5s])",
     "legendFormat": "Avg Processing Time"
    }
   ]
  }
 ]
}