{
 "title": "Fraud Detection Dashboard Full",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "us_state",
    "query": "label_values(scorings_total, us_state)"
   },
   {
    "name": "merch",
    "query": "label_values(scorings_total, merch)"
   }
  ]
 },
 "panels": [
  {
   "title": "Доля мошеннических транзакций",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(fraud_detected_total{us_state=~\"$us_state\", merch=~\"$merch\"}) / sum(scorings_total{us_state=~\"$us_state\", merch=~\"$merch\"})",
     "legendFormat": "Fraud Rate"
    }
   ]
  },
  {
   "title": "TPS (Транзакции в секунду)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(scorings_total{us_state=~\"$us_state\", merch=~\"$merch\"}[$__rate_interval])",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Распределение скоров мошенничества",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(scoring_fraud_score_bucket{us_state=~\"$us_state\", merch=~\"$merch\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Доля фрода по категориям (последние 1000)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "fraud_rate_by_category{us_state=~\"$us_state\", merch=~\"$merch\"}",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Среднее время записи в БД",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(scoring_db_write_seconds_sum{us_state=~\"$us_state\", merch=~\"$merch\"}[$__rate_interval]) / rate(scoring_db_write_seconds_count{us_state=~\"$us_state\", merch=~\"$merch\"}[$__rate_interval])",
     "legendFormat": "Avg DB Write Time"
    }
   ]
  },
  {
   "title": "Детали транзакций",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "scorings_total{us_state=~\"$us_state\", merch=~\"$merch\"}"
    }
   ]
  }
 ]
}